---
notifications:
  email:
  - team@appwrite.io

dist: xenial

language: shell

arch:
  - amd64
  - arm64

os: linux

before_install:
  - curl -fsSL https://get.docker.com | sh
  - echo '{"experimental":"enabled"}' | sudo tee /etc/docker/daemon.json
  - mkdir -p $HOME/.docker
  - echo '{"experimental":"enabled"}' | sudo tee $HOME/.docker/config.json
  - sudo service docker start

install:
  - docker-compose up -d

script:
  - docker ps -a
  - docker-compose logs request-catcher
  - >
    if : >/dev/tcp/localhost/5000; then
      echo 'Connection available.'
      travis_terminate 0
    else
      echo 'Connection unavailable.'
      travis_terminate 1
    fi
